export const mockUsers = [
     {
          id: '1',
          email: 'user@example.com',
          name: 'John Doe',
          role: 'user',
          isActive: true,
          walletBalance: 2500.00,
          joinDate: '2023-01-15',
     },
     {
          id: '2',
          email: 'admin@example.com',
          name: 'Jane Smith',
          role: 'admin',
          isActive: true,
          joinDate: '2022-06-10',
     },
     {
          id: '3',
          email: 'superadmin@example.com',
          name: 'Mike Johnson',
          role: 'super-admin',
          isActive: true,
          joinDate: '2021-03-01',
     },
     {
          id: '4',
          email: 'alice@example.com',
          name: 'Alice Brown',
          role: 'user',
          isActive: true,
          walletBalance: 1200.50,
          joinDate: '2023-05-20',
     },
     {
          id: '5',
          email: 'bob@example.com',
          name: 'Bob Wilson',
          role: 'user',
          isActive: false,
          walletBalance: 500.00,
          joinDate: '2023-02-28',
     },
     {
          id: '6',
          email: 'sara@example.com',
          name: 'Sara Davis',
          role: 'user',
          isActive: true,
          walletBalance: 3200.75,
          joinDate: '2023-07-15',
     },
     {
          id: '7',
          email: 'david@example.com',
          name: 'David Miller',
          role: 'admin',
          isActive: true,
          joinDate: '2022-11-30',
     },
     {
          id: '8',
          email: 'emma@example.com',
          name: 'Emma Wilson',
          role: 'user',
          isActive: true,
          walletBalance: 1800.25,
          joinDate: '2023-03-12',
     },
     {
          id: '9',
          email: 'ryan@example.com',
          name: 'Ryan Chen',
          role: 'user',
          isActive: true,
          walletBalance: 4200.00,
          joinDate: '2023-01-05',
     },
     {
          id: '10',
          email: 'lisa@example.com',
          name: 'Lisa Taylor',
          role: 'user',
          isActive: false,
          walletBalance: 750.00,
          joinDate: '2023-04-18',
     },
];

export const mockTransactions = [
     {
          id: '1',
          userId: '1',
          amount: 150.00,
          type: 'credit',
          description: 'Deposit from bank account',
          date: '2024-01-15T10:30:00Z',
          status: 'completed',
     },
     {
          id: '2',
          userId: '1',
          amount: 75.50,
          type: 'debit',
          description: 'Online purchase - Amazon',
          date: '2024-01-14T15:45:00Z',
          status: 'completed',
     },
     {
          id: '3',
          userId: '4',
          amount: 200.00,
          type: 'credit',
          description: 'Salary deposit',
          date: '2024-01-13T09:00:00Z',
          status: 'completed',
     },
     {
          id: '4',
          userId: '1',
          amount: 25.00,
          type: 'debit',
          description: 'Coffee subscription',
          date: '2024-01-12T08:15:00Z',
          status: 'pending',
     },
     {
          id: '5',
          userId: '4',
          amount: 300.00,
          type: 'debit',
          description: 'Rent payment',
          date: '2024-01-10T12:00:00Z',
          status: 'completed',
     },
     {
          id: '6',
          userId: '6',
          amount: 500.00,
          type: 'credit',
          description: 'Freelance payment',
          date: '2024-01-09T14:20:00Z',
          status: 'completed',
     },
     {
          id: '7',
          userId: '8',
          amount: 100.00,
          type: 'debit',
          description: 'Grocery shopping',
          date: '2024-01-08T17:30:00Z',
          status: 'completed',
     },
     {
          id: '8',
          userId: '9',
          amount: 250.00,
          type: 'credit',
          description: 'Investment dividend',
          date: '2024-01-07T11:45:00Z',
          status: 'completed',
     },
     {
          id: '9',
          userId: '1',
          amount: 50.00,
          type: 'credit',
          description: 'Refund - Clothing return',
          date: '2024-01-06T13:15:00Z',
          status: 'completed',
     },
     {
          id: '10',
          userId: '6',
          amount: 150.00,
          type: 'debit',
          description: 'Electricity bill',
          date: '2024-01-05T09:30:00Z',
          status: 'completed',
     },
     {
          id: '11',
          userId: '4',
          amount: 80.00,
          type: 'debit',
          description: 'Internet bill',
          date: '2024-01-04T10:00:00Z',
          status: 'completed',
     },
     {
          id: '12',
          userId: '8',
          amount: 200.00,
          type: 'credit',
          description: 'Client payment',
          date: '2024-01-03T14:45:00Z',
          status: 'completed',
     },
     {
          id: '13',
          userId: '9',
          amount: 350.00,
          type: 'debit',
          description: 'Car payment',
          date: '2024-01-02T16:20:00Z',
          status: 'completed',
     },
     {
          id: '14',
          userId: '1',
          amount: 45.00,
          type: 'debit',
          description: 'Dining out',
          date: '2024-01-01T19:30:00Z',
          status: 'completed',
     },
     {
          id: '15',
          userId: '6',
          amount: 120.00,
          type: 'credit',
          description: 'Referral bonus',
          date: '2023-12-31T11:10:00Z',
          status: 'completed',
     },
     {
          id: '16',
          userId: '4',
          amount: 90.00,
          type: 'debit',
          description: 'Phone bill',
          date: '2023-12-30T10:30:00Z',
          status: 'completed',
     },
     {
          id: '17',
          userId: '8',
          amount: 180.00,
          type: 'debit',
          description: 'Gym membership',
          date: '2023-12-29T09:15:00Z',
          status: 'completed',
     },
     {
          id: '18',
          userId: '9',
          amount: 300.00,
          type: 'credit',
          description: 'Stock sale',
          date: '2023-12-28T14:00:00Z',
          status: 'completed',
     },
     {
          id: '19',
          userId: '1',
          amount: 65.00,
          type: 'debit',
          description: 'Online course',
          date: '2023-12-27T16:45:00Z',
          status: 'completed',
     },
     {
          id: '20',
          userId: '6',
          amount: 200.00,
          type: 'debit',
          description: 'Vacation booking',
          date: '2023-12-26T12:30:00Z',
          status: 'pending',
     },
];

export const mockCredentials = {
     'user@example.com': 'password123',
     'admin@example.com': 'admin123',
     'superadmin@example.com': 'super123',
     'alice@example.com': 'alicepass',
     'bob@example.com': 'bobpass',
     'sara@example.com': 'sarapass',
     'david@example.com': 'davidpass',
     'emma@example.com': 'emmapass',
     'ryan@example.com': 'ryanpass',
     'lisa@example.com': 'lisapass',
};